from pathlib import Path

from oasis import app, db
from oasis.openapi import spec


@app.cli.command()
def init_db():
    """Initialize database."""
    import oasis.models
    db.create_all()


@app.cli.command()
def gen():
    """Generate OpenAPI specification."""
    spec_path = Path(__file__).parent.joinpath('../openapi.yaml').resolve()
    with open(spec_path, 'w') as f:
        f.write('# DO NOT EDIT\n')
        f.write('# Auto generated by "flask gen"\n')
        f.write('\n')
        f.write(spec.to_yaml())

    app.logger.info(f'Generated {spec_path}')
