CREATE TABLE user (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
  ,username VARCHAR(255) NOT NULL
  ,password VARCHAR(255) NOT NULL
  ,nickname VARCHAR(255) NOT NULL
  ,created_at DATETIME NOT NULL
  ,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  ,UNIQUE KEY uk_username (username)
);

INSERT INTO user VALUES (1, 'admin', '{bcrypt}$2a$10$f4aQLof9kgM8mzJIP7a.Vuc3WYcQK8brcL6hrHdCdkzTH8AppEpOm', 'Jerry', NOW(), NOW());
